-- MIQQIL TANKS — схема рейтинга (Neon / Lakebase Postgres)
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  nick VARCHAR(16) UNIQUE NOT NULL,
  pass_hash TEXT NOT NULL,
  rating INTEGER NOT NULL DEFAULT 1000,
  kills INTEGER NOT NULL DEFAULT 0,
  matches INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS matches (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  vehicle VARCHAR(16) NOT NULL DEFAULT 't42',
  placement INTEGER NOT NULL,
  total INTEGER NOT NULL,
  kills INTEGER NOT NULL DEFAULT 0,
  rating_after INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_users_rating ON users (rating DESC);
CREATE INDEX IF NOT EXISTS idx_matches_user ON matches (user_id);
